name: metamorph
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk-Regular.ttf
        - asset: fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600



